[package]
name = "rs-plugin-tmdb"
version = "0.15.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
chrono = { version = "0.4", default-features = false, features = ["std"] }
extism-pdk = "1.4.1"
rs-plugin-common-interfaces = { git = "https://github.com/neckaros/rs-plugin-common-interfaces", rev = "9d85ee9ae32188063c5c7b018b0d25cae37ee81b", version = "0.40.0" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
regex = "1"

[dev-dependencies]
extism = "1"
